---

name: DevOps Project Pipeline

on: 
  push:
    branches: 
      - main

jobs: 
  publish: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Short SHA
        run: |
          echo "SHORT_SHA=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
        
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devops-project-docker-repo:${{ env.SHORT_SHA }} .

      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/devops-project-docker-repo:${{ env.SHORT_SHA }}

      - name: Configure Git Auth
        run: |
          git config --local user.email ${{ secrets.USER_EMAIL }}
          git config --local user.name ${{ secrets.USERNAME }}
        
      - name: Update Helm Chart With New Image Tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./devops-project-time-printer/values.yaml
          git add ./devops-project-time-printer/values.yaml
          git commit -m "Updated image tag to ${{ env.SHORT_SHA }}"
          git push 